/** Central React Query keys. Prefix-based invalidation: invalidating `qk.agents` also hits `qk.agent(id)`. */
export const qk = {
  bootstrap: ["bootstrap"] as unknown[],
  authStatus: ["auth-status"] as unknown[],
  settings: ["settings"] as unknown[],
  notifications: ["notifications"] as unknown[],
  audit: ["audit"] as unknown[],
  logs: ["logs"] as unknown[],
  logOverview: ["logs", "overview"] as unknown[],
  logEntries: (level: string, search: string) => ["logs", "entries", level, search],
  doctor: ["doctor"] as unknown[],
  claudeUpdate: ["doctor", "claude-update"] as unknown[],
  models: ["models"] as unknown[],
  vaultStatus: ["vault", "status"] as unknown[],
  appSecrets: ["vault", "secrets"] as unknown[],
  credentials: ["credentials"] as unknown[],
  credentialList: (workspaceId: string, search: string) => ["credentials", "list", workspaceId, search],
  totp: ["totp"] as unknown[],
  totpList: (workspaceId: string) => ["totp", "list", workspaceId],
  totpCodes: ["totp", "codes"] as unknown[],
  workspaces: ["workspaces"] as unknown[],
  agents: ["agents"] as unknown[],
  agentList: (workspaceId: string) => ["agents", "list", workspaceId],
  agent: (id: string) => ["agents", "detail", id],
  agentFilesAll: ["agents", "files"] as unknown[],
  agentFiles: (id: string, path: string) => ["agents", "files", id, path],
  agentFileAll: ["agents", "file"] as unknown[],
  agentFile: (id: string, path: string) => ["agents", "file", id, path],
  agentCommitsAll: ["agents", "commits"] as unknown[],
  agentCommits: (id: string) => ["agents", "commits", id],
  agentCommands: (id: string) => ["agents", "commands", id],
  agentTemplates: ["agent-templates"] as unknown[],
  /** Dreams (memory consolidation); invalidating the root refreshes every overview and detail. */
  dreams: ["dreams"] as unknown[],
  agentDreams: (agentId: string) => ["dreams", "agent", agentId],
  dream: (id: string) => ["dreams", "detail", id],
  routines: ["routines"] as unknown[],
  routineList: (agentId: string) => ["routines", "list", agentId],
  /** Automation events; the third segment is the routine id or "all" (see realtime.ts). */
  automationEvents: ["automation-events"] as unknown[],
  automationEventList: (routineId: string, limit: number) => ["automation-events", "list", routineId, limit],
  conversationsAll: ["conversations"] as unknown[],
  conversationLists: ["conversations", "list"] as unknown[],
  conversations: (agentId: string, search: string) => ["conversations", "list", agentId, search],
  archivedConversationLists: ["conversations", "archived"] as unknown[],
  archivedConversations: (agentId: string, search: string) => ["conversations", "archived", agentId, search],
  conversation: (id: string) => ["conversations", "detail", id],
  /** Times agents set to continue their chats on their own. */
  followups: ["followups"] as unknown[],
  runs: ["runs"] as unknown[],
  runList: (agentId: string, status: string) => ["runs", "list", agentId, status],
  run: (id: string) => ["runs", "detail", id],
  missingLogins: ["missing-logins"] as unknown[],
  mcpServers: ["mcp-servers"] as unknown[],
  composio: ["composio"] as unknown[],
  composioStatus: ["composio", "status"] as unknown[],
  composioToolkits: (search: string, category: string) => ["composio", "toolkits", search, category],
  composioConnections: ["composio", "connections"] as unknown[],
  composioTriggerTypes: (toolkit: string) => ["composio", "trigger-types", toolkit],
  composioTriggerType: (slug: string) => ["composio", "trigger-type", slug],
  messaging: ["messaging"] as unknown[],
  messagingList: ["messaging", "list"] as unknown[],
  messagingUsers: (id: string) => ["messaging", "users", id],
  messagingChats: (id: string) => ["messaging", "chats", id],
  browserProfiles: ["browser-profiles"] as unknown[],
  computer: ["computer"] as unknown[],
  computerStatus: ["computer", "status"] as unknown[],
  computerSources: ["computer", "sources"] as unknown[],
  computerThumbnail: (view: string, size: number) => ["computer", "thumbnail", view, size],
  /** macOS VMs; the list is patched in place by `vm.updated` events (see realtime.ts). */
  vms: ["vms"] as unknown[],
  vmList: ["vms", "list"] as unknown[],
  vmStatus: ["vms", "status"] as unknown[],
  vmScreen: (id: string, size: number) => ["vm-screen", id, size],
  chromeProfiles: ["chrome-profiles"] as unknown[],
  folders: ["folders"] as unknown[],
  folderList: (path: string, hidden: boolean) => ["folders", "list", path, hidden],
  recentFolders: ["folders", "recent"] as unknown[],
};
