/** Central React Query keys. Prefix-based invalidation: invalidating `qk.agents` also hits `qk.agent(id)`. */
export const qk = {
  bootstrap: ["bootstrap"] as unknown[],
  /** "Needs you" — under `bootstrap`, so whatever refreshes the counts refreshes the list. */
  attention: ["bootstrap", "attention"] as unknown[],
  away: (since: string, until: string) => ["away", since, until],
  authStatus: ["auth-status"] as unknown[],
  settings: ["settings"] as unknown[],
  notifications: ["notifications"] as unknown[],
  audit: ["audit"] as unknown[],
  logs: ["logs"] as unknown[],
  logOverview: ["logs", "overview"] as unknown[],
  logEntries: (level: string, search: string) => ["logs", "entries", level, search],
  doctor: ["doctor"] as unknown[],
  claudeUpdate: ["doctor", "claude-update"] as unknown[],
  permissions: ["doctor", "permissions"] as unknown[],
  toolUpdates: ["doctor", "updates"] as unknown[],
  maintenance: ["doctor", "maintenance"] as unknown[],
  cleanup: ["cleanup"] as unknown[],
  models: ["models"] as unknown[],
  vaultStatus: ["vault", "status"] as unknown[],
  appSecrets: ["vault", "secrets"] as unknown[],
  credentials: ["credentials"] as unknown[],
  credentialList: (workspaceId: string, search: string) => ["credentials", "list", workspaceId, search],
  totp: ["totp"] as unknown[],
  totpList: (workspaceId: string) => ["totp", "list", workspaceId],
  totpCodes: ["totp", "codes"] as unknown[],
  workspaces: ["workspaces"] as unknown[],
  /** Task board; lists are patched in place by `task.updated` events (see realtime.ts). */
  tasks: ["tasks"] as unknown[],
  taskList: (workspaceId: string) => ["tasks", "list", workspaceId],
  archivedTaskList: (workspaceId: string) => ["tasks", "archived", workspaceId],
  /** Its own root: updaters assume every query under ["tasks"] holds Task[]. */
  taskEvents: (id: string) => ["task-events", id],
  agents: ["agents"] as unknown[],
  agentList: (workspaceId: string) => ["agents", "list", workspaceId],
  agent: (id: string) => ["agents", "detail", id],
  agentFilesAll: ["agents", "files"] as unknown[],
  agentFiles: (id: string, path: string) => ["agents", "files", id, path],
  agentFileAll: ["agents", "file"] as unknown[],
  agentFile: (id: string, path: string) => ["agents", "file", id, path],
  agentCommitsAll: ["agents", "commits"] as unknown[],
  agentCommits: (id: string) => ["agents", "commits", id],
  agentCommands: (id: string) => ["agents", "commands", id],
  agentTemplates: ["agent-templates"] as unknown[],
  teamTemplates: ["team-templates"] as unknown[],
  goals: ["goals"] as unknown[],
  goalList: (workspaceId: string) => ["goals", "list", workspaceId],
  /** Dreams (memory consolidation); invalidating the root refreshes every overview and detail. */
  dreams: ["dreams"] as unknown[],
  agentDreams: (agentId: string) => ["dreams", "agent", agentId],
  dream: (id: string) => ["dreams", "detail", id],
  routines: ["routines"] as unknown[],
  routineList: (agentId: string) => ["routines", "list", agentId],
  /** Automation events; the third segment is the routine id or "all" (see realtime.ts). */
  automationEvents: ["automation-events"] as unknown[],
  automationEventList: (routineId: string, limit: number) => ["automation-events", "list", routineId, limit],
  conversationsAll: ["conversations"] as unknown[],
  conversationLists: ["conversations", "list"] as unknown[],
  conversations: (agentId: string, search: string) => ["conversations", "list", agentId, search],
  archivedConversationLists: ["conversations", "archived"] as unknown[],
  archivedConversations: (agentId: string, search: string) => ["conversations", "archived", agentId, search],
  conversation: (id: string) => ["conversations", "detail", id],
  /** Times agents set to continue their chats on their own. */
  followups: ["followups"] as unknown[],
  runs: ["runs"] as unknown[],
  /** Spend and budgets (refreshed when runs end or stand still, and when settings or agents change). */
  spend: ["spend"] as unknown[],
  spendReport: (period: string, agentId: string | null) => ["spend", "report", period, agentId ?? "all"] as const,
  budgets: ["spend", "budgets"] as unknown[],
  /** Runs handed over by a run (under `runs`, so run events refresh them). */
  runChildren: (runId: string) => ["runs", "children", runId] as const,
  runList: (agentId: string, status: string) => ["runs", "list", agentId, status],
  run: (id: string) => ["runs", "detail", id],
  missingLogins: ["missing-logins"] as unknown[],
  questions: ["questions"] as unknown[],
  mcpServers: ["mcp-servers"] as unknown[],
  apiTools: ["api-tools"] as unknown[],
  composio: ["composio"] as unknown[],
  composioStatus: ["composio", "status"] as unknown[],
  composioToolkits: (search: string, category: string) => ["composio", "toolkits", search, category],
  composioConnections: ["composio", "connections"] as unknown[],
  composioTriggerTypes: (toolkit: string) => ["composio", "trigger-types", toolkit],
  composioTriggerType: (slug: string) => ["composio", "trigger-type", slug],
  messaging: ["messaging"] as unknown[],
  messagingList: ["messaging", "list"] as unknown[],
  messagingUsers: (id: string) => ["messaging", "users", id],
  messagingChats: (id: string) => ["messaging", "chats", id],
  browserProfiles: ["browser-profiles"] as unknown[],
  botCheck: ["browser-bot-check"] as unknown[],
  computer: ["computer"] as unknown[],
  computerStatus: ["computer", "status"] as unknown[],
  computerSources: ["computer", "sources"] as unknown[],
  computerThumbnail: (view: string, size: number) => ["computer", "thumbnail", view, size],
  /** macOS VMs; the list is patched in place by `vm.updated` events (see realtime.ts). */
  vms: ["vms"] as unknown[],
  vmList: ["vms", "list"] as unknown[],
  vmStatus: ["vms", "status"] as unknown[],
  vmScreen: (id: string, size: number) => ["vm-screen", id, size],
  sshServers: ["ssh-servers"] as unknown[],
  sshLocalKeys: ["ssh-local-keys"] as unknown[],
  mods: ["mods"] as unknown[],
  /** Not under ["mods"]: the gallery doesn't change when a mod does. */
  modTemplates: ["mod-templates"] as unknown[],
  /** Phone access: Tailscale status and paired phones. */
  mobile: ["mobile"] as unknown[],
  connectors: ["connectors"] as unknown[],
  /** Runners (other computers that work for this one); the list is patched in place by `runner.updated` events. */
  runners: ["runners"] as unknown[],
  /** Not under ["runners"]: refreshing the list must not re-run a runner's checks. */
  runnerHealth: (id: string) => ["runner-health", id],
  runnerSources: (id: string) => ["runner-sources", id],
  /** Godmode Cloud link status; billing sits under it, so invalidating `cloud` refreshes both. */
  cloud: ["cloud"] as unknown[],
  cloudBilling: ["cloud", "billing"] as unknown[],
  license: ["license"] as unknown[],
  /** What agents used on this computer over the last `days` days. */
  usage: (days: number) => ["usage", days],
  chromeProfiles: ["chrome-profiles"] as unknown[],
  folders: ["folders"] as unknown[],
  folderList: (path: string, hidden: boolean) => ["folders", "list", path, hidden],
  recentFolders: ["folders", "recent"] as unknown[],
  chatFiles: (conversationId: string, refs: string) => ["chat-files", conversationId, refs],
};
