/** Central React Query keys. Prefix-based invalidation: invalidating `qk.agents` also hits `qk.agent(id)`. */
export const qk = {
  bootstrap: ["bootstrap"] as unknown[],
  authStatus: ["auth-status"] as unknown[],
  settings: ["settings"] as unknown[],
  notifications: ["notifications"] as unknown[],
  audit: ["audit"] as unknown[],
  doctor: ["doctor"] as unknown[],
  models: ["models"] as unknown[],
  vaultStatus: ["vault", "status"] as unknown[],
  appSecrets: ["vault", "secrets"] as unknown[],
  credentials: ["credentials"] as unknown[],
  credentialList: (workspaceId: string, search: string) => ["credentials", "list", workspaceId, search],
  totp: ["totp"] as unknown[],
  totpList: (workspaceId: string) => ["totp", "list", workspaceId],
  totpCodes: ["totp", "codes"] as unknown[],
  workspaces: ["workspaces"] as unknown[],
  agents: ["agents"] as unknown[],
  agentList: (workspaceId: string) => ["agents", "list", workspaceId],
  agent: (id: string) => ["agents", "detail", id],
  agentFiles: (id: string, path: string) => ["agents", "files", id, path],
  agentFile: (id: string, path: string) => ["agents", "file", id, path],
  agentCommits: (id: string) => ["agents", "commits", id],
  agentCommands: (id: string) => ["agents", "commands", id],
  agentTemplates: ["agent-templates"] as unknown[],
  routines: ["routines"] as unknown[],
  routineList: (agentId: string) => ["routines", "list", agentId],
  conversationsAll: ["conversations"] as unknown[],
  conversations: (agentId: string, search: string) => ["conversations", "list", agentId, search],
  conversation: (id: string) => ["conversations", "detail", id],
  runs: ["runs"] as unknown[],
  runList: (agentId: string, status: string) => ["runs", "list", agentId, status],
  run: (id: string) => ["runs", "detail", id],
  missingLogins: ["missing-logins"] as unknown[],
  mcpServers: ["mcp-servers"] as unknown[],
  composio: ["composio"] as unknown[],
  composioStatus: ["composio", "status"] as unknown[],
  composioToolkits: (search: string, category: string) => ["composio", "toolkits", search, category],
  composioConnections: ["composio", "connections"] as unknown[],
  browserProfiles: ["browser-profiles"] as unknown[],
  chromeProfiles: ["chrome-profiles"] as unknown[],
};
