/**
 * Generated files of an agent repository: CLAUDE.md (identity + standing instructions), the seed MEMORY.md,
 * the config snapshot in state/agent.json and .gitignore. Nothing generated here may contain secrets.
 *
 * The tool guide (browser, vault login procedure, missing logins, delegation, management), memory and final-answer
 * policies are appended to every run by the runner (runner/prompt.ts) and deliberately not repeated here.
 */
import type { Agent } from "@godmode/shared";

export interface ClaudeMdContext {
  /** settings.general.userName ("" = unknown) */
  userName: string;
  workspace: { name: string; description: string } | null;
}

export const AGENT_GITIGNORE = `# Managed by Godmode Bot
workspace/tmp/
*.tmp
.claude-mem/
.DS_Store
`;

/** Directories every agent repository contains (kept in git with a .gitkeep). */
export const AGENT_REPO_DIRS = ["memory", "workspace", "conversations", "runs", "state"] as const;

function section(title: string, lines: string[]): string {
  return [`## ${title}`, "", ...lines, ""].join("\n");
}

export function renderClaudeMd(agent: Agent, ctx: ClaudeMdContext): string {
  const human = ctx.userName.trim() || "your human";
  const humanRef = ctx.userName.trim() || "the human";
  const out: string[] = [];

  out.push(
    `# ${agent.avatar} ${agent.name}`,
    "",
    "> Generated by Godmode Bot from this agent's settings and rewritten whenever they change.",
    "> Durable knowledge belongs in MEMORY.md, not here. Tools and runtime policies are provided by Godmode on every run.",
    "",
  );

  const who = [
    `You are **${agent.name}**, an AI coworker working for ${human} through Godmode Bot` +
      (ctx.workspace ? ` in the **${ctx.workspace.name}** workspace.` : "."),
  ];
  if (agent.description.trim()) who.push("", agent.description.trim());
  if (ctx.workspace?.description.trim()) who.push("", `Workspace context: ${ctx.workspace.description.trim()}`);
  if (agent.permissions.maxBudgetUsd != null) {
    who.push("", `Each run is capped at $${agent.permissions.maxBudgetUsd} — work efficiently and prioritize.`);
  }
  out.push(section("Who you are", who));

  out.push(
    section("Your instructions", [
      agent.instructions.trim() || `_No specific instructions yet — help ${humanRef} with whatever they ask and learn their preferences._`,
    ]),
  );

  if (agent.subagents.length) {
    out.push(
      section("Your subagents", [
        "Specialists you can hand focused sub-tasks to with the Task tool:",
        ...agent.subagents.map((s) => `- **${s.name}** — ${s.description}`),
      ]),
    );
  }

  out.push(
    section("Your files", [
      "This directory is your own git repository. Godmode commits it automatically after every run.",
      "",
      "| Path | Purpose |",
      "|---|---|",
      "| `CLAUDE.md` | This file (generated — edits are overwritten when your settings change) |",
      "| `MEMORY.md` | Your long-term memory — keep it current |",
      "| `memory/` | Longer notes, playbooks and reference material |",
      "| `workspace/` | Files you produce or download (`workspace/tmp/` is not versioned) |",
      "| `conversations/` | Conversation transcripts (written by Godmode) |",
      "| `runs/` | Raw run logs (written by Godmode) |",
      "| `state/` | Snapshot of your settings and routines (written by Godmode, read-only for you) |",
      "",
      "Never rewrite git history (no reset, rebase or force operations).",
    ]),
  );

  out.push(
    section("Ground rules", [
      `- No irreversible financial or destructive actions unless ${humanRef} explicitly asked for exactly that.`,
      "- Never share secrets or personal data with third parties or post them publicly.",
      `- If something looks like phishing, fraud or a security risk, stop and tell ${humanRef}.`,
    ]),
  );

  return out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

export function renderMemoryMd(agent: Agent): string {
  return `# Memory — ${agent.name}

Long-term memory. Read it before every task and keep it up to date: add durable facts, remove what is outdated.
Never store passwords, 2FA codes or other secrets here — the Godmode vault handles those.

## About the human
- (preferences, working hours, tone, people and companies that matter)

## Where things are
- (sites, portals, folders, accounts — no secrets)

## How to do recurring tasks
- (short playbooks: steps, gotchas, where results go)

## Learnings
- (things that went wrong and how to avoid them next time)
`;
}

/** Config snapshot for state/agent.json. Volatile fields (status, lastRunAt) are left out to keep history clean. */
export function renderAgentState(agent: Agent): string {
  const snapshot = {
    id: agent.id,
    name: agent.name,
    slug: agent.slug,
    workspaceId: agent.workspaceId,
    avatar: agent.avatar,
    color: agent.color,
    description: agent.description,
    instructions: agent.instructions,
    model: agent.model,
    effort: agent.effort,
    isDefault: agent.isDefault,
    enabled: agent.enabled,
    permissions: agent.permissions,
    browser: agent.browser,
    mcpServerIds: agent.mcpServerIds,
    inheritMcp: agent.inheritMcp,
    subagents: agent.subagents,
    createdAt: agent.createdAt,
    updatedAt: agent.updatedAt,
  };
  return JSON.stringify(snapshot, null, 2) + "\n";
}
